language: node_js
node_js:
  - 12.10.0

addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - npm test
  - npm test:cucumber
